import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Weather App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <header>
        <img src="/assets/images/logo.svg" alt="weather-now-logo" />
        <button>
          <img src="/assets/images/icon-units.svg" alt="unit-icon" />
          Units
          <img src="/assets/images/icon-dropdown.svg" alt="dropdown-icon" />
        </button>
      </header>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
      <footer>
        <p>This is a Frontend Mentor Project. Check them out <a href="https://www.frontendmentor.io/challenges/weather-app-K1FhddVm49">here</a> !</p>
      </footer>
    </html>
  );
}
